//! Traits that define the core extension points for `easypdf-rust`.
//!
//! Includes `PdfModel`, `PdfReadListener`, `PdfWriteHandler`, `PdfConverter`,
//! `PdfEngine`, `EngineCapabilities`, and `CapabilityLevel`.

use crate::error::Result;

/// Trait for types that can be rendered as PDF content.
///
/// This is typically derived via `#[derive(PdfModel)]` rather than
/// implemented manually. It maps a Rust struct to PDF elements.
pub trait PdfModel {
    /// Render this model into PDF content.
    ///
    /// The implementation is generated by the derive macro and handles
    /// layout, positioning, and style application.
    ///
    /// # Errors
    ///
    /// Returns an error when model conversion or content rendering fails.
    fn render(&self) -> Result<Vec<RenderedElement>>;

    /// Return metadata for this model (page size, orientation, margins, etc.).
    fn metadata(&self) -> PdfModelMetadata;

    /// Return field descriptors for form-filling and data-mapping use cases.
    ///
    /// Each field annotated with `#[pdf(field = "...")]` or similar attributes
    /// generates a descriptor. The default implementation returns an empty vec.
    fn field_descriptors(&self) -> Vec<PdfFieldDescriptor> {
        Vec::new()
    }
}

/// Descriptor for a single field in a [`PdfModel`], generated by the derive macro.
///
/// Carries metadata from `#[pdf(field = "...", order = N, ...)]` attributes
/// and is used by the template filler and validation logic.
#[derive(Debug, Clone)]
pub struct PdfFieldDescriptor {
    /// PDF form field name this maps to.
    pub field_name: String,
    /// Rust field name.
    pub rust_field_name: String,
    /// Display order (lower = earlier).
    pub order: u32,
    /// Optional format string (e.g. "YYYY-MM-DD" for dates).
    pub format: Option<String>,
    /// Default value expression (as a string), if specified.
    pub default_value: Option<String>,
    /// Whether this field is required.
    pub required: bool,
    /// Whether this is a nested sub-model.
    pub nested: bool,
}

impl PdfFieldDescriptor {
    /// Create a new field descriptor with minimal required fields.
    #[must_use]
    pub fn new(field_name: impl Into<String>, rust_field_name: impl Into<String>) -> Self {
        Self {
            field_name: field_name.into(),
            rust_field_name: rust_field_name.into(),
            order: u32::MAX,
            format: None,
            default_value: None,
            required: false,
            nested: false,
        }
    }
}

/// Metadata associated with a `PdfModel` (typically from `#[pdf(...)]` attributes).
#[derive(Debug, Clone)]
pub struct PdfModelMetadata {
    /// Page size for the model.
    pub page_size: crate::enums::PageSize,
    /// Page orientation.
    pub orientation: crate::enums::Orientation,
    /// Page margins in points.
    pub margins: f64,
}

impl Default for PdfModelMetadata {
    fn default() -> Self {
        Self {
            page_size: crate::enums::PageSize::A4,
            orientation: crate::enums::Orientation::default(),
            margins: 72.0,
        }
    }
}

/// A rendered element produced by a [`PdfModel`].
///
/// This is the output of `PdfModel::render()`, representing one
/// positioned piece of content on a PDF page.
#[derive(Debug, Clone)]
pub enum RenderedElement {
    /// A text element at the given (x, y) position.
    Text {
        /// X coordinate in PDF points from bottom-left.
        x: f64,
        /// Y coordinate in PDF points from bottom-left.
        y: f64,
        /// The text content with formatting.
        text: crate::content::PdfText,
    },
    /// A table at the given (x, y) position.
    Table {
        /// X coordinate of table top-left.
        x: f64,
        /// Y coordinate of table top-left.
        y: f64,
        /// The table data and configuration.
        table: crate::content::PdfTable,
    },
    /// An image at the given (x, y) position.
    Image {
        /// X coordinate from bottom-left.
        x: f64,
        /// Y coordinate from bottom-left.
        y: f64,
        /// The image data.
        image: crate::content::PdfImage,
    },
}

// --- PdfReadListener ---

/// Event-driven listener for PDF reading operations.
///
/// Analogous to `ReadListener<T>` in easyexcel-rs. Called for
/// each page or text block encountered during reading.
///
/// This trait requires `Send` so that listeners can be used across thread
/// boundaries in async or parallel reading pipelines. Implementors that
/// hold non-`Send` state should wrap it in a `Mutex` or similar.
pub trait PdfReadListener: Send {
    /// Called when a page starts being processed.
    ///
    /// # Errors
    ///
    /// Implementations may stop processing by returning an error.
    fn on_page_start(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called for each text block extracted from a page.
    ///
    /// # Errors
    ///
    /// Implementations may stop processing by returning an error.
    fn on_text(&mut self, page_number: usize, text: &str) -> Result<()>;

    /// Called when a page has been fully processed.
    ///
    /// # Errors
    ///
    /// Implementations may stop processing by returning an error.
    fn on_page_end(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called after all pages have been processed.
    ///
    /// # Errors
    ///
    /// Implementations may report finalization failure.
    fn on_document_end(&mut self) -> Result<()> {
        Ok(())
    }
}

// --- PdfWriteHandler ---

/// Lifecycle hooks for PDF writing operations.
///
/// Analogous to `WriteHandler` in easyexcel-rs. Handlers are
/// called in order (by priority) at each stage of document creation.
pub trait PdfWriteHandler: Send {
    /// Called before the document is created.
    ///
    /// # Errors
    ///
    /// Implementations may abort document creation.
    fn before_document(&mut self) -> Result<()> {
        Ok(())
    }

    /// Called before a new page is started.
    ///
    /// # Errors
    ///
    /// Implementations may abort page creation.
    fn before_page(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called after a page is completed.
    ///
    /// # Errors
    ///
    /// Implementations may report page finalization failure.
    fn after_page(&mut self, page_number: usize) -> Result<()> {
        let _ = page_number;
        Ok(())
    }

    /// Called after the document is finalized.
    ///
    /// # Errors
    ///
    /// Implementations may report document finalization failure.
    fn after_document(&mut self) -> Result<()> {
        Ok(())
    }
}

// --- PdfConverter ---

/// Bidirectional converter between a Rust type `T` and a PDF string representation.
///
/// Analogous to `Converter<T>` in easyexcel-rs.
pub trait PdfConverter<T>: Send {
    /// Convert a Rust value to its PDF string representation.
    ///
    /// # Errors
    ///
    /// Returns an error when the value cannot be represented.
    fn to_pdf_string(&self, value: &T) -> Result<String>;

    /// Convert a PDF string representation back to a Rust value.
    ///
    /// # Errors
    ///
    /// Returns an error when the string cannot be parsed.
    #[allow(clippy::wrong_self_convention)]
    fn from_pdf_string(&self, s: &str) -> Result<T>;
}

/// Blanket implementation so that `Box<dyn PdfConverter<T>>` can be used
/// wherever `PdfConverter<T>` is expected (e.g., in `ConverterRegistry::register`).
impl<T> PdfConverter<T> for Box<dyn PdfConverter<T>> {
    fn to_pdf_string(&self, value: &T) -> Result<String> {
        (**self).to_pdf_string(value)
    }

    fn from_pdf_string(&self, s: &str) -> Result<T> {
        (**self).from_pdf_string(s)
    }
}

// --- PdfEngine (C1) ---

/// Abstract PDF engine interface for backend swapping.
///
/// Allows different PDF backends (lopdf, printpdf, justpdf) to be used
/// interchangeably. Currently experimental — full abstraction awaits
/// a second mature engine implementation.
pub trait PdfEngine: Send + Sync {
    /// Human-readable engine name.
    fn name(&self) -> &str;

    /// Features supported by this engine.
    fn capabilities(&self) -> EngineCapabilities;
}

/// Describes which operations a PDF engine supports.
#[derive(Debug, Clone, Copy, Default)]
#[allow(clippy::struct_excessive_bools)]
pub struct EngineCapabilities {
    /// Can create new PDF documents from scratch.
    pub create: bool,
    /// Can read and parse existing PDF documents.
    pub read: bool,
    /// Can manipulate (merge, split, rotate) existing PDFs.
    pub manipulate: bool,
    /// Can fill form fields in PDF templates.
    pub fill_forms: bool,
    /// Supports encryption.
    pub encrypt: bool,
    /// Supports digital signatures.
    pub sign: bool,
    /// Supports PDF/A validation.
    pub pdfa: bool,
}

impl EngineCapabilities {
    /// lopdf capabilities.
    #[must_use]
    pub const fn lopdf() -> Self {
        Self {
            create: false,
            read: true,
            manipulate: true,
            fill_forms: true,
            encrypt: false,
            sign: false,
            pdfa: false,
        }
    }

    /// printpdf capabilities.
    #[must_use]
    pub const fn printpdf() -> Self {
        Self {
            create: true,
            read: false,
            manipulate: false,
            fill_forms: false,
            encrypt: false,
            sign: false,
            pdfa: false,
        }
    }

    /// Convert to a [`DetailedEngineCapabilities`] with [`CapabilityLevel`] values.
    ///
    /// Boolean `true` maps to [`CapabilityLevel::Structural`]; `false` maps to
    /// [`CapabilityLevel::None`].
    #[must_use]
    pub const fn to_detailed(&self) -> DetailedEngineCapabilities {
        DetailedEngineCapabilities {
            text_extraction: if self.read {
                CapabilityLevel::Structural
            } else {
                CapabilityLevel::None
            },
            metadata: if self.read {
                CapabilityLevel::Structural
            } else {
                CapabilityLevel::None
            },
            image_extraction: if self.read {
                CapabilityLevel::Heuristic
            } else {
                CapabilityLevel::None
            },
            table_detection: if self.read {
                CapabilityLevel::Heuristic
            } else {
                CapabilityLevel::None
            },
            rendering: if self.create {
                CapabilityLevel::Structural
            } else {
                CapabilityLevel::None
            },
        }
    }
}

/// Graduated capability level for fine-grained engine feature reporting.
///
/// Unlike a boolean, this communicates *how well* an engine supports a feature,
/// enabling downstream code (e.g., markdown processor chains) to pick the best
/// available engine or fall back gracefully.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[non_exhaustive]
pub enum CapabilityLevel {
    /// Feature is not supported.
    #[default]
    None,
    /// Feature is supported via heuristic or approximate methods.
    Heuristic,
    /// Feature is supported with full structural accuracy.
    Structural,
    /// Feature is supported with cloud-accelerated or AI-assisted processing.
    Cloud,
}

impl CapabilityLevel {
    /// Return whether this level represents any degree of support (not `None`).
    #[must_use]
    pub const fn is_supported(&self) -> bool {
        !matches!(self, Self::None)
    }
}

/// Detailed engine capabilities using graduated [`CapabilityLevel`] values.
///
/// This complements the boolean-based [`EngineCapabilities`] for scenarios where
/// the *quality* of support matters (e.g., selecting an extraction strategy in
/// the markdown processor chain).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct DetailedEngineCapabilities {
    /// Quality of text extraction support.
    pub text_extraction: CapabilityLevel,
    /// Quality of metadata (XMP, document info) extraction.
    pub metadata: CapabilityLevel,
    /// Quality of image extraction support.
    pub image_extraction: CapabilityLevel,
    /// Quality of table detection and extraction.
    pub table_detection: CapabilityLevel,
    /// Quality of rendering (document creation) support.
    pub rendering: CapabilityLevel,
}

#[cfg(test)]
#[allow(clippy::uninlined_format_args, clippy::float_cmp)]
mod tests {
    use super::*;

    #[test]
    fn capability_level_ordering() {
        assert!(CapabilityLevel::None < CapabilityLevel::Heuristic);
        assert!(CapabilityLevel::Heuristic < CapabilityLevel::Structural);
        assert!(CapabilityLevel::Structural < CapabilityLevel::Cloud);
    }

    #[test]
    fn capability_level_default_is_none() {
        assert_eq!(CapabilityLevel::default(), CapabilityLevel::None);
    }

    #[test]
    fn capability_level_is_supported() {
        assert!(!CapabilityLevel::None.is_supported());
        assert!(CapabilityLevel::Heuristic.is_supported());
        assert!(CapabilityLevel::Structural.is_supported());
        assert!(CapabilityLevel::Cloud.is_supported());
    }

    #[test]
    fn capability_level_debug() {
        assert_eq!(format!("{:?}", CapabilityLevel::Cloud), "Cloud");
    }

    #[test]
    fn detailed_capabilities_default() {
        let dc = DetailedEngineCapabilities::default();
        assert_eq!(dc.text_extraction, CapabilityLevel::None);
        assert_eq!(dc.metadata, CapabilityLevel::None);
        assert_eq!(dc.image_extraction, CapabilityLevel::None);
        assert_eq!(dc.table_detection, CapabilityLevel::None);
        assert_eq!(dc.rendering, CapabilityLevel::None);
    }

    #[test]
    fn engine_capabilities_to_detailed_lopdf() {
        let caps = EngineCapabilities::lopdf();
        let detailed = caps.to_detailed();
        assert_eq!(detailed.text_extraction, CapabilityLevel::Structural);
        assert_eq!(detailed.metadata, CapabilityLevel::Structural);
        assert_eq!(detailed.image_extraction, CapabilityLevel::Heuristic);
        assert_eq!(detailed.table_detection, CapabilityLevel::Heuristic);
        assert_eq!(detailed.rendering, CapabilityLevel::None);
    }

    #[test]
    fn engine_capabilities_to_detailed_printpdf() {
        let caps = EngineCapabilities::printpdf();
        let detailed = caps.to_detailed();
        assert_eq!(detailed.text_extraction, CapabilityLevel::None);
        assert_eq!(detailed.metadata, CapabilityLevel::None);
        assert_eq!(detailed.image_extraction, CapabilityLevel::None);
        assert_eq!(detailed.table_detection, CapabilityLevel::None);
        assert_eq!(detailed.rendering, CapabilityLevel::Structural);
    }

    #[test]
    fn detailed_capabilities_equality() {
        let a = DetailedEngineCapabilities {
            text_extraction: CapabilityLevel::Structural,
            ..Default::default()
        };
        let b = DetailedEngineCapabilities {
            text_extraction: CapabilityLevel::Structural,
            ..Default::default()
        };
        assert_eq!(a, b);
    }

    #[test]
    fn detailed_capabilities_inequality() {
        let a = DetailedEngineCapabilities {
            text_extraction: CapabilityLevel::Structural,
            ..Default::default()
        };
        let b = DetailedEngineCapabilities {
            text_extraction: CapabilityLevel::Heuristic,
            ..Default::default()
        };
        assert_ne!(a, b);
    }

    #[test]
    fn detailed_capabilities_debug() {
        let dc = DetailedEngineCapabilities::default();
        let dbg = format!("{:?}", dc);
        assert!(dbg.contains("DetailedEngineCapabilities"));
    }

    #[test]
    fn detailed_capabilities_clone() {
        let dc = DetailedEngineCapabilities {
            text_extraction: CapabilityLevel::Cloud,
            metadata: CapabilityLevel::Structural,
            image_extraction: CapabilityLevel::Heuristic,
            table_detection: CapabilityLevel::None,
            rendering: CapabilityLevel::Structural,
        };
        let cloned = dc;
        assert_eq!(dc, cloned);
    }

    #[test]
    fn engine_capabilities_default() {
        let caps = EngineCapabilities::default();
        assert!(!caps.create);
        assert!(!caps.read);
        assert!(!caps.manipulate);
        assert!(!caps.fill_forms);
        assert!(!caps.encrypt);
        assert!(!caps.sign);
        assert!(!caps.pdfa);
    }

    #[test]
    fn engine_capabilities_debug() {
        let caps = EngineCapabilities::lopdf();
        let dbg = format!("{:?}", caps);
        assert!(dbg.contains("EngineCapabilities"));
    }

    #[test]
    fn engine_capabilities_clone() {
        let caps = EngineCapabilities::printpdf();
        let cloned = caps;
        assert_eq!(caps.create, cloned.create);
    }

    #[test]
    fn pdf_field_descriptor_new() {
        let desc = PdfFieldDescriptor::new("pdf_name", "rust_name");
        assert_eq!(desc.field_name, "pdf_name");
        assert_eq!(desc.rust_field_name, "rust_name");
        assert_eq!(desc.order, u32::MAX);
        assert!(desc.format.is_none());
        assert!(desc.default_value.is_none());
        assert!(!desc.required);
        assert!(!desc.nested);
    }

    #[test]
    fn pdf_field_descriptor_debug() {
        let desc = PdfFieldDescriptor::new("f", "r");
        let dbg = format!("{:?}", desc);
        assert!(dbg.contains("PdfFieldDescriptor"));
    }

    #[test]
    fn pdf_field_descriptor_clone() {
        let desc = PdfFieldDescriptor::new("f", "r");
        let cloned = desc.clone();
        assert_eq!(desc.field_name, cloned.field_name);
    }

    #[test]
    fn pdf_model_metadata_default() {
        let meta = PdfModelMetadata::default();
        assert_eq!(meta.page_size, crate::enums::PageSize::A4);
        assert_eq!(meta.margins, 72.0);
    }

    #[test]
    fn pdf_model_metadata_debug() {
        let meta = PdfModelMetadata::default();
        let dbg = format!("{:?}", meta);
        assert!(dbg.contains("PdfModelMetadata"));
    }

    #[test]
    fn pdf_model_metadata_clone() {
        let meta = PdfModelMetadata::default();
        let cloned = meta.clone();
        assert_eq!(meta.margins, cloned.margins);
    }

    #[test]
    fn capability_level_clone_copy() {
        let level = CapabilityLevel::Structural;
        let copied = level;
        assert_eq!(level, copied);
    }

    #[test]
    fn capability_level_hash() {
        use std::collections::HashSet;
        let mut set = HashSet::new();
        set.insert(CapabilityLevel::None);
        set.insert(CapabilityLevel::None);
        set.insert(CapabilityLevel::Heuristic);
        assert_eq!(set.len(), 2);
    }

    #[test]
    fn engine_capabilities_to_detailed_custom() {
        let caps = EngineCapabilities {
            create: true,
            read: true,
            manipulate: false,
            fill_forms: false,
            encrypt: false,
            sign: false,
            pdfa: false,
        };
        let detailed = caps.to_detailed();
        assert_eq!(detailed.text_extraction, CapabilityLevel::Structural);
        assert_eq!(detailed.metadata, CapabilityLevel::Structural);
        assert_eq!(detailed.image_extraction, CapabilityLevel::Heuristic);
        assert_eq!(detailed.table_detection, CapabilityLevel::Heuristic);
        assert_eq!(detailed.rendering, CapabilityLevel::Structural);
    }

    #[test]
    fn engine_capabilities_to_detailed_none() {
        let caps = EngineCapabilities::default();
        let detailed = caps.to_detailed();
        assert_eq!(detailed.text_extraction, CapabilityLevel::None);
        assert_eq!(detailed.metadata, CapabilityLevel::None);
        assert_eq!(detailed.image_extraction, CapabilityLevel::None);
        assert_eq!(detailed.table_detection, CapabilityLevel::None);
        assert_eq!(detailed.rendering, CapabilityLevel::None);
    }
}
