//! Real-world PDF scenario tests.
//!
//! Covers: large documents, table text, multi-column layout, encrypted PDF
//! detection, `AcroForm` recognition, image-only pages, nested objects,
//! and corrupted xref repair.
//!
//! These tests use the synthetic PDFs generated by `generate_samples`
//! and `generate_special_pdfs` binaries.

use std::path::PathBuf;

use easypdf::PdfInput;
use easypdf::prelude::*;
use easypdf::{RepairOptions, attempt_repair, is_likely_corrupt};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn samples_dir() -> PathBuf {
    manifest_dir().join("samples")
}

fn sample_path(name: &str) -> PathBuf {
    let path = samples_dir().join(name);
    assert!(
        path.exists(),
        "sample PDF not found: {name}. Run `cargo run -p easypdf-test --bin generate_samples` \
         and `cargo run -p easypdf-test --bin generate_special_pdfs` first.",
    );
    path
}

// =========================================================================
// Category A: Complex synthetic PDFs
// =========================================================================

/// Verify that a 100-page document can be opened and its page count is correct.
#[test]
fn large_100page_page_count() {
    let path = sample_path("large_100page.pdf");
    let count = EasyPdf::read(&path)
        .page_count()
        .unwrap_or_else(|e| panic!("failed to get page count: {e}"));
    assert_eq!(count, 100, "expected 100 pages in large_100page.pdf");
}

/// Verify that text extraction from a 100-page document succeeds and
/// contains content from multiple pages.
#[test]
fn large_100page_text_extraction() {
    let path = sample_path("large_100page.pdf");
    let text = EasyPdf::read(&path)
        .extract_text()
        .unwrap_or_else(|e| panic!("failed to extract text from large_100page.pdf: {e}"));
    // Should contain at least page markers from early and late pages
    assert!(
        text.contains("Page 1") || text.contains("Stress test"),
        "expected content from page 1 in extracted text"
    );
    assert!(
        text.len() > 100,
        "expected substantial text from 100-page doc, got {} bytes",
        text.len()
    );
}

/// Verify that pipe-delimited table text is preserved through extraction.
#[test]
fn table_text_preserved() {
    let path = sample_path("with_table_text.pdf");
    let text = EasyPdf::read(&path)
        .extract_text()
        .unwrap_or_else(|e| panic!("failed to extract text: {e}"));
    // The table text should contain pipe characters from the table
    assert!(
        text.contains('|') || text.contains("Name") || text.contains("Alice"),
        "expected table content with pipe-separated data, got: {}",
        &text[..text.len().min(200)]
    );
}

/// Verify that multi-column heuristic text is extractable.
#[test]
fn multi_column_text_extractable() {
    let path = sample_path("multi_column_heuristic.pdf");
    let text = EasyPdf::read(&path)
        .extract_text()
        .unwrap_or_else(|e| panic!("failed to extract text: {e}"));
    // Should contain content from both columns
    assert!(
        text.contains("Introduction") || text.contains("Results") || text.contains("Conclusion"),
        "expected content from multi-column layout, got: {}",
        &text[..text.len().min(200)]
    );
}

// =========================================================================
// Category B: Special structure PDFs
// =========================================================================

/// Verify that a PDF with a dummy `/Encrypt` dictionary is detected.
///
/// The reader should either:
/// - Return an `Encryption` error, or
/// - Return a `Parse` error indicating the document is encrypted
///
/// This tests that the reader does not silently ignore encryption markers.
#[test]
fn encrypted_pdf_detected() {
    let path = sample_path("encrypted_dummy.pdf");
    let result = EasyPdf::read(&path).extract_text();
    // The reader should either fail (encryption not supported) or
    // return a degraded result. Either way, it must not panic.
    match result {
        Ok(_text) => {
            // If it succeeds, that is also acceptable -- lopdf may ignore
            // the Encrypt dict and still extract text from the content stream.
        }
        Err(e) => {
            let msg = format!("{e}");
            // Accept any error: Encryption, Parse, or other
            assert!(
                msg.contains("encrypt")
                    || msg.contains("Encrypt")
                    || msg.contains("parse")
                    || msg.contains("Parse")
                    || msg.contains("Encrypted"),
                "expected encryption-related or parse error, got: {msg}"
            );
        }
    }
}

/// Verify that a PDF with `/AcroForm` fields can be opened and its
/// structure is readable.
#[test]
fn acroform_pdf_opens() {
    let path = sample_path("with_acroform.pdf");
    let count = EasyPdf::read(&path)
        .page_count()
        .unwrap_or_else(|e| panic!("failed to open AcroForm PDF: {e}"));
    assert_eq!(count, 1, "expected 1 page in AcroForm PDF");
}

/// Verify that text extraction from an image-only page returns
/// empty or minimal text (no text operators in content stream).
#[test]
fn image_only_page_no_text() {
    let path = sample_path("image_only.pdf");
    let text = EasyPdf::read(&path)
        .extract_text()
        .unwrap_or_else(|e| panic!("failed to read image-only PDF: {e}"));
    // An image-only page should have no extractable text
    let trimmed = text.trim();
    assert!(
        trimmed.is_empty() || trimmed.len() < 20,
        "expected empty or minimal text from image-only page, got: {trimmed}"
    );
}

/// Verify that a PDF with deeply nested objects can be opened and
/// its page count is correct.
#[test]
fn nested_objects_readable() {
    let path = sample_path("nested_objects.pdf");
    let count = EasyPdf::read(&path)
        .page_count()
        .unwrap_or_else(|e| panic!("failed to read nested objects PDF: {e}"));
    assert_eq!(count, 1, "expected 1 page in nested objects PDF");

    let text = EasyPdf::read(&path)
        .extract_text()
        .unwrap_or_else(|e| panic!("failed to extract text from nested objects PDF: {e}"));
    assert!(
        text.contains("Nested") || text.contains("Test"),
        "expected text content from nested objects PDF"
    );
}

/// Verify that a PDF with a corrupted xref table triggers the
/// repair path or produces a meaningful error.
///
/// This tests the `is_likely_corrupt` / `attempt_repair` pipeline.
#[test]
fn corrupted_xref_handled() {
    let path = sample_path("corrupted_xref.pdf");

    // First, try opening normally -- should either succeed (lopdf auto-repair)
    // or fail with a parse error.
    let normal_result = EasyPdf::read(&path).extract_text();

    if normal_result.is_err() {
        // Normal open failed, which is expected for a corrupted xref.
        // Now verify the repair path works.
        let input = PdfInput::from_path(&path);
        let corrupt = is_likely_corrupt(&input);
        assert!(corrupt, "corrupted PDF should be detected as corrupt");

        // Attempt repair
        let repair_result = attempt_repair(&input, &RepairOptions::default());
        if let Ok(repaired_bytes) = repair_result {
            // Repaired bytes should be parseable
            let reader =
                PdfReader::from_bytes(repaired_bytes).expect("repaired PDF should be parseable");
            let _text = reader
                .extract_text()
                .expect("text extraction from repaired PDF should succeed");
        } else {
            // Repair failed -- this is also a valid outcome for
            // severely corrupted PDFs. Just log it.
            eprintln!("repair failed (acceptable): {}", repair_result.unwrap_err());
        }
    }
}

/// Verify that all 11 sample PDFs (3 original + 3 category A + 5 category B)
/// can be listed from the samples directory.
#[test]
fn all_sample_pdfs_present() {
    let dir = samples_dir();
    let expected = [
        "minimal.pdf",
        "multipage.pdf",
        "with-metadata.pdf",
        "large_100page.pdf",
        "with_table_text.pdf",
        "multi_column_heuristic.pdf",
        "encrypted_dummy.pdf",
        "with_acroform.pdf",
        "image_only.pdf",
        "nested_objects.pdf",
        "corrupted_xref.pdf",
    ];
    for name in &expected {
        let path = dir.join(name);
        assert!(
            path.exists(),
            "expected sample PDF '{name}' not found in {}",
            dir.display()
        );
        let size = std::fs::metadata(&path)
            .unwrap_or_else(|e| panic!("failed to stat {name}: {e}"))
            .len();
        assert!(size > 0, "sample PDF '{name}' is empty (0 bytes)");
        assert!(
            size < 1_000_000,
            "sample PDF '{name}' is {size} bytes, exceeds 1 MB limit"
        );
    }
}
